### ISSUE TITLE
plot.py error: "dataset input should have multiple elements`

### ISSUE THREAD

**Issue by rspreafico-vir** [broadinstitute/rnaseqc#23]
Hi there,

I have successfully run rnaseqc on a BAM file, and now I was attempting to use `plot.py` from the official Docker container to plot metrics:

```
root@012f04b3af10:/Users/rspreafico/Desktop/quantseq/out/rnaseqc# python3 /scripts/plot.py . out
Detected 1 samples
Loading metrics
Generating Fragment Size KDE
Generating QC figures
Traceback (most recent call last):
  File "/scripts/plot.py", line 285, in <module>
    main(parser.parse_args())
  File "/scripts/plot.py", line 154, in main
    ms=16
  File "/scripts/metrics.py", line 138, in plot_qc_figures
    metrics_plot(v, cohort_s, ylim=[0, 0.55], title='Intergenic rate', threshold=intergenic_rate, threshold_dir='gt', **metrics_args)
  File "/scripts/metrics.py", line 64, in metrics_plot
    sns.kdeplot(v, ax=dax, vertical=True, legend=False, shade=True)
  File "/usr/local/lib/python3.5/dist-packages/seaborn/distributions.py", line 691, in kdeplot
    cumulative=cumulative, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/seaborn/distributions.py", line 294, in _univariate_kdeplot
    x, y = _scipy_univariate_kde(data, bw, gridsize, cut, clip)
  File "/usr/local/lib/python3.5/dist-packages/seaborn/distributions.py", line 366, in _scipy_univariate_kde
    kde = stats.gaussian_kde(data, bw_method=bw)
  File "/usr/local/lib/python3.5/dist-packages/scipy/stats/kde.py", line 195, in __init__
    raise ValueError("`dataset` input should have multiple elements.")
ValueError: `dataset` input should have multiple elements.
```

Here is my `mapped.bam.metrics.tsv` file:

```
Sample  mapped.bam
Mapping Rate    0.964203
Unique Rate of Mapped   1
Duplicate Rate of Mapped        0
Base Mismatch   0.00281886
End 1 Mapping Rate      0
End 2 Mapping Rate      0
End 1 Mismatch Rate     nan
End 2 Mismatch Rate     nan
Expression Profiling Efficiency 0.834477
High Quality Rate       0
Exonic Rate     0.869553
Intronic Rate   0.00322584
Intergenic Rate 0.0628047
Intragenic Rate 0.872779
Ambiguous Alignment Rate        0.0644161
High Quality Exonic Rate        nan
High Quality Intronic Rate      nan
High Quality Intergenic Rate    nan
High Quality Intragenic Rate    nan
High Quality Ambiguous Alignment Rate   nan
Discard Rate    0
rRNA Rate       0
End 1 Sense Rate        nan
End 2 Sense Rate        nan
Avg. Splits per Read    0.256174
Alternative Alignments  0
Chimeric Reads  0
Duplicate Reads 0
End 1 Antisense 0
End 2 Antisense 0
End 1 Bases     0
End 2 Bases     0
End 1 Mapped Reads      0
End 2 Mapped Reads      0
End 1 Mismatches        0
End 2 Mismatches        0
End 1 Sense     0
End 2 Sense     0
Exonic Reads    11942791
Failed Vendor QC        67407
High Quality Reads      0
Intergenic Reads        862584
Intragenic Reads        11987096
Ambiguous Reads 884716
Intronic Reads  44305
Low Mapping Quality     14244304
Low Quality Reads       13734396
Mapped Duplicate Reads  0
Mapped Reads    13734396
Mapped Unique Reads     13734396
Mismatched Bases        1935764
Reads excluded from exon counts 0
Reads used for Intron/Exon counts       13734396
rRNA Reads      0
Total Bases     686719800
Total Mapped Pairs      0
Total Reads     14311711
Unique Mapping, Vendor QC Passed Reads  14244304
Unpaired Reads  14244304
Read Length     50
Genes Detected  0
Estimated Library Complexity    0
Mean 3' bias    0
Median 3' bias  0
3' bias Std     0
3' bias MAD_Std 0
3' Bias, 25th Percentile        0
3' Bias, 75th Percentile        0
Median of Avg Transcript Coverage       0
Median of Transcript Coverage Std       0
Median of Transcript Coverage CV        0
Median Exon CV  0
Exon CV MAD     0
```

**Comment by agraubert** [comment]
The plotting code is designed to compare different samples. Most of the plots are simply displaying different values from the metrics files over all of the given samples.  The only plot which would be useful for a single sample is the KDE of fragment size.

If you're interested in just viewing the fragment size KDE for a single sample, I'd be happy to provide you with code that's designed for a single sample.

I apologize that there are not clear error messages to describe this problem. I will fix that in the next update to RNA-SeQC
